### PR TITLE
Add to_hex and from_hex for the mockchain key.

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by NicolasDP** [comment]
@qnikst please, add rustfmt to your editor, I'd like to stop seeing commits for rust formatting.

**Comment by qnikst** [comment]
applied `rustfmt` (no additional commits involved). Should I do anything about cardano::redeem::Error here?

**Comment by NicolasDP** [comment]
I don't see the problem of the `redeem::Error` ...

**Comment by mzabaluev** [comment]
It's OK, let's use the single domain error type unless we have a good reason to invent a parsing-specific error type.

**Pull request merged**
