### PR TITLE
allow transaction without inputs or outputs

### PR DESCRIPTION
**Pull request by NicolasDP**
the fee/balance will do the work

FYI @dkijania and @CodeSandwich

### CODE REVIEW

**Comment by CodeSandwich** [comment]
Is transaction with no inputs, no outputs and linear fee without constant value valid? Will it start being accepted?

What about shredder transaction with inputs but no output, is it ever acceptable?

**Comment by NicolasDP** [comment]
multiple cases:

1. no inputs, no outputs and no certificates are covered by the constant fee setting. They will be rejected;
2. everything else requires an exact balance. It needs to include fees and the necessary inputs/outputs

**Comment by CodeSandwich** [comment]
Is the exact balance requirement already enforced? We still haven't solved the problem of positive balance with value lower than fee for addition of another output.

**Comment by vincenthz** [comment]
@CodeSandwich it's enforced at the moment, although yes there's some case that are quite complicated.. which I personally think is endemic to the problem of using utxo instead of accounts

**Pull request merged**
