### PR TITLE
artifacting of test results

### PR DESCRIPTION
**Pull request by amias-iohk**
updates to test runs to explictly archive test results

### CODE REVIEW

**Comment by amias-iohk** [comment]
this change has been shown to work ok , lets merge it to master.

**Comment by NicolasDP** [comment]
can you help me there, what is this doing ?

**Comment by amias-iohk** [comment]
it is ensuring the test results are preserved as an artefact , this enables the insights view to work.

**Comment by NicolasDP** [comment]
I don't see stored artifacts : https://circleci.com/gh/input-output-hk/rust-cardano/304#artifacts/containers/0

**Pull request merged**
